---
roles:
  - name: geerlingguy.postgresql
    src: https://github.com/geerlingguy/ansible-role-postgresql
    version: master

  - name: geerlingguy.jenkins
    src: https://github.com/geerlingguy/ansible-role-jenkins
    version: master

  - name: geerlingguy.gitlab
    src: https://github.com/geerlingguy/ansible-role-gitlab
    version: master

  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
    version: master

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.crypto
